travis:
  secure:
    BINSTAR_TOKEN: TB1hfCgLqqnCuCP7jQSBMZXxvoDz5PCv/t1y6ixw9KZJlDRtWNrGdHYwYzcipIVSonQ5oBYac1k+0sWro80sy6G2jh61jm4RdxuWkWAazgaSWw84T7LPhCtrK7Mj3jvy9K4pTN/kK7n/Fz4zkOEqZpJf3EOMvXgvIf0cYJK0d+b0M4oSdQ2t7bS21zBNMX19Maiye91xPtST00qmZ4zUzzC3NmFzx4mjadOpqsrBnugbHPjzkK/wou02bJwcNUVhFOESDYIKRs1+t6hKr4ZtDdTXeNOi2YfSSRpBGpacKIX0rI6CdaPdrBVE8tA5Rt/UtuAjFIqOpZq0UbQmsBtyVS+21duE0uOynAUXrX7cxRGYFsHNuVRaGV4NELdtcNWAu92WRCRaUJuneYQS8noGk5I57HMFMpydK+mxLFkCOJ77qFZmHuNoBfgzLFhftTnz9OpEtIEqJGMh0dwD9u9ksEuT4iX5SRirVZrt6DKpubISf4kW9YIgpvMswQgimL1Zkf1AGJyFOt2t9j/4qmvrQOUG4JDyU1z/VnNgNp+PSSX54RAGSr9obl8p5ZwIoWT9evBAMlB0igxoqsMNH4F4+CApgyplUDzAxJfui0A0OyO4i+xdgvmStWkK8Z+CuG/uUbNvJ0wTr3715idLgBNPWwVZYXrpPzVOrD7tgN+TvwI=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
