travis:
  secure:
    BINSTAR_TOKEN: o5eSrKSRe/oB/SbCp1vakFKtn3OhA4Ll5U6y5bkO+eYpZUs0fj00zCB1D/y8wR+YgKVJ4c3kTSo1OYQjlT80AkZdGYh3iXYv80OkOrhqtzuRK6gZ3w54tOAInpOqTRJYqAX3kyaK+gX13MHClpFQUYJJK3O8IPgiPgWz8LjBwM3YdHGlxecJCwm7slaao/aGWYtLgn/JfVc+mYN6X7WRUmNGf4tcasO1GW2zdUT+mjY6U8AaJWTAT00RfuIAvIBI3gpcDMfmxmi1UaEfNKxY8axLS0P5xO/qzWHwOT9kRBiq5d9VnD//34CNXDC2+VyGm01BB3Bt1jDr7/kY3zjtVogJQ2ne+0FFgPtzh5C/1u582Egn6QGT/JBpmGbGdgOjfvN3vUbRwuAECzBY8AOd6QhMuPRboZTRxSEUblJWckTySc6uKfY5GPK/mFcq3hr90yVQoOpp96nvfuXq5AnmAV5WVQV6el2JCw/pAW4Ix4j8woClSkaRPD+AQvzbQjHBKIf3kbOnM0vKmUW8JnHlkEwKW2IzIoNQBwbTSJ4d9ZkJtA2jf4ZgJ2j1T5/i8CDDyinJqa0aEAroIIU3hD9vOrFiZpxWjhXe2FgximjtPFMc+uL85EYVp8KtImvBqpTjNGVlc/REWISMXa59YsVk/5nz+M0GteIKW45B9YxW+Uk=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
