travis:
  secure:
    BINSTAR_TOKEN: kPy3KRt4QtDEc5KQo1QWma0srmmAxafN1cSpWrphhGecvChBFCIyixjHb3fWLZAoSn965GCExToYUMy+WvaS9N3GuqZ0vncyvGcQkYGm5qlTZTK1WH8ZVmBCDACoGc/gxhGr9H2EaeoLpEFrDIutkf9yNPyT1rgIRTxTd6L6bSgpTHj3x+MukNBcU32+P9XC+zs6+rigu0mhEGA8UfetwCnX2gUH/KbVfQfqivsVfPY73YsWiGnOKtVk+W2nj/Qgr53kXSNkGE/mQeWQBcFCrKclgM8uXp71DCzXgVFVpZk25n2QucYWNX2aYVYh2tgULl+yhLimIlRjIAXnc8uWIZ0HlBihIL3JBzKc7UaGwUw1yWo/KZac8/qYcu9dEU2DJkkWAUCC2yR87iCB0snWLPHwqNlMGe1K/WlNKZrVYXC/y8WL+P9WOebdffDV0IdBgKhsN3DDJB6hVg8dfpvHXf89jUskGFixFbkb6YqSZDnSnT4Eiw0O9t+zdkEEuBjmDgo1yD/ki3/+Ww5Jhmm3rLmfoIJcRvTmD/F0sMszNoJB88e0lvRO2Hc9fRAnBideT/keZmoaqTCtK1UeOUAOl8awCoxL5z3nE5mrPWho6Uk6ErLV+FLz3rMAPFi/dYZvLG5OooQF8WUzdGtaDcR6cmqVU++/j9hXsKHac5NsGqM=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
