travis:
  secure:
    BINSTAR_TOKEN: DvBCVd6wpWcAbvWoDLOBAWep6mSGlzPRKxp9zUXbqwBDl4MGMRZhuNN0rEEu7TOlDVsgC2zy/06kvoJ6Y6jH7LjPwY997psIPZn43qO9LHS7GjqxND/F7Q7SmAARnQLfn5qQICOc7F1dYUQRP8m/quu7s8PceCCkrX7IIOnDGivBPmylNAne9s7yYLeVPFFhDM2eyqvel7QiXoRlfOd8KTgnY1ulVP04VeHLJDPms4Wst9EIb6In/9IxhHiEDPtz1wBFBW0ardIlLaIZ75byANJcqYiQYT4tVgIv7Z7ebD+euKhcogj+Tlp2PuCcarkk4yIP4KZvtpUQXsX51qw2aHWGqLkwKrlp0kesMBgf2G/2ycAkTNgI+qtmukhy11cJChkTTub3VATlTX+OUH44icNu3kw39UMPElawA4p6ARIZW3wIMj3IAD+G4xziWwYrqE89gsm8hf/0f4RWYDuE1M+oslZlw1QUnKiGzo7MXmoJVgNrRLWx0wXwdQM1+hYoXZB4apgR90jvOUIjPZd2GUhvw8Y4329cwUkb7W7dHi5qvPuWZ+aw1zkMdUgWjvE25VXlDX6RlAu+h9322qLWyek2ZkO3xbaz/8DZq81mvUxVQgqXAFukAsciucWeQcfV0uUCeG5H8Q3cqPGyyU1U+r4w3kbRJpWfXjEzUMAl3fE=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
