travis:
  secure:
    BINSTAR_TOKEN: McslXx2QlUcDdM9k94DD1mT8dmjYtB2+lPR6cVHv/cQoBcJtoZdBLYRi6Zivk+vxc5XWOL2nSna1SF6/fDSINmIc08pja9n1/JXhR3Okjzpm4NMiMLkbnHKSjDWi3uMEBA+5sw/75+SK1kHuuFEZPjiuaSHBnAwJU1o0XtP6oRe4coPcuBs7m6nZ9n0EFb8DU8IwrH2aggT/XnKki/1QczRklIMXGjLJMLUEQ2FxDpYa08hAa9w8Emofpze2gVCvm9cyzWrgOqLMGEwuZWYipiF7ONnbytEyv8UKkh69n7RgfZLBEIiCTHifiCT4u0lvDgfo7HOctM2ngIET49lEaICSZUZ7HItyT+mIMfhMsWrN9elxdnaCpf/7dM3/LYfWZQraNzvK+fAgfKyhlXYj9n7/J+h/OWeBdVkzMPlX0I79EV9Xx82TwiDLkwTKbfHJRE+GIlNaa/kSp2YJFz9ylvkBm5VL2im3PniWm6die9ud10t54ROvNTM3qipw5uwhkganu60EX0okBQYK6QkCUo8t06OUDh/8SCeRHrJa5Qvtfcu0AQlzr48MdpZP6VcprEC2zverDSpQeXFekjS72/E6+S2nR7ZD9Gy3jAECN8kG4SiIXFEuXLk8BhexGNrrAP/IDKq8NkxGnP6kN4dzgVedHbuBKlj0EVxSz1wdWPE=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
