appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: ntENUCoMAccNc3GGlbNgi2zRVYJ2Y4A6EKfXyiV/Iqsvllu5t6bHzJF91Obp8oCgkM4BDgK/xU+Nb19yFcKr0uo4D6gLXV8Y1ZD6tqRQQOe5bop6aiSdOun+nxK4oS1RT3i989TJpUsIGl3JFH4BeFkputur1nuw2bHBO6hulZoBZIlIZGCYoSTdxhPmsNzZ6ENZy0jrVEh4XfCkZBb8zD5D6VCnB8iBeaezoBg9qulOKjiJ8pi3LsxxPbdhjzkdc7I7PMq5NtJeMKuaJ3OKU1JrDot9D2MZM856d32Au9LaPkf8ZQ3EQ3jExCdS7Z/KDe4L/9b1kDIThP+LcOGlJRq+8o8DD9eqTq552pAXemUEU8ZXAxwYXKMy2TU/sGLoYczVwLcI8AOKZOEepgaD2py772BajGhSM62sT1Ff5J+Zy58WKQPPlSvMVud+r7fPHP154opJA6Z6E2OMEOnNMRqBgL0SQTIodOfc1edNLtqDu//ErG4UcoCZfa4nDkIiqtzX8wr+KEzgk6TVw0o8MEyK2i0Vx80WgbdG8UKva/Pu7vhFR2dqc4d/dxv8cil/WonF02Q92wJMX4DKYVlZYqNwivA91iI+r7NkesaQtYgk3Aj3JBZMGK4wIvQJ5reFvvENvMiiAcfPqpY6JU1DTlLAR3VHkBMhqZtZcHMz88k=}
